# Generated by Django 5.2 on 2025-04-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='full_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_name',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_name',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
