# Generated by Django 5.2 on 2025-05-14 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tickets_reserved',
        ),
    ]
