# Generated by Django 5.2 on 2025-05-14 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_remove_ticket_tickets_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrival_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 21, 0, 0)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='destination',
            field=models.CharField(default='dfsf', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='origin',
            field=models.CharField(default='dssg', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='train_number',
            field=models.CharField(default=25, max_length=20),
            preserve_default=False,
        ),
    ]
