# Generated by Django 5.2 on 2025-05-21 04:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_ticket_is_canceled_alter_trip_arrival_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='applied_discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 21, 4, 17, 13, 415404, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_canceled_by_company',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='catering_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='TripReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('customer', 'مشتری'), ('seller', 'فروشنده'), ('admin', 'ادمین')], max_length=10)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='booking.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
