# Generated by Django 5.2 on 2025-05-21 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_ticket_applied_discount_percent_ticket_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 21, 4, 17, 44, 205961, tzinfo=datetime.timezone.utc)),
        ),
    ]
