# Generated by Django 5.2 on 2025-05-21 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_ticket_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='birth_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 21, 4, 18, 33, 236379, tzinfo=datetime.timezone.utc)),
        ),
    ]
