# Generated by Django 5.2 on 2025-05-21 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_ticket_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
