# Generated by Django 5.2 on 2025-05-21 06:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_alter_ticket_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripreview',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
